### ISSUE TITLE
Failed to setup for MariaDb

### ISSUE THREAD

**Issue by HalibutGitWiz** [makinacorpus/DbToolsBundle#215]
I want to try this tool which seems pretty awesome, but I can't figure out how to setup for MariaDB.

When I do `vendor/bin/db-tools check` I get:
```
In BridgeFactory.php line 196:

  could not find driver
```

Here is my _composer.json_:

```json
{
    "require": {
        "makinacorpus/db-tools-bundle": "^2.0",
        "db-tools-bundle/pack-fr-fr": "^0.4.0"
    }
}
```

And my _db_tools.config.yaml_:

```yaml
connections: "mysql://user:password@localhost:3306?version=11.4"
backup_binary: '/usr/bin/mariadb-dump'
restore_binary: '/usr/bin/mariadb'
```

I specified `backup_binary` and `restore_binary` in case it was looking for `mysql` and `mysqldump` since MariaDB changed those binaries' names recently, I get the same result with or without these two lines.

I'm running PHP 8.4.4 and MariaDB 11.4.5.

I do PHP development everyday on this computer, so I'm confident my PHP / MariaDB install is working. Both mysqli and PDO extensions are installed and active.
