### ISSUE TITLE
Anonymization - Add "collection" notion

### ISSUE THREAD

**Issue by SimonMellerin** [makinacorpus/DbToolsBundle#42]
The main idea is to tag anonymized column targets using one or more "collection" name:

```yml
anonymization:
    default:
        user:
            country: 
                anonymizer: fr_fr.prenom
                collection: other_collection
            prenom: 
                anonymizer: fr_fr.prenom
                collection: [my_collection, other_collection]
            nom: fr_fr.nom
```

Which enables partial anonymization across many tables in a single connection, such as:

```sh
php bin/console db-tools:anonymize --local --collection=some_collection --collection=other_collection
```

We had a use case in the past, where we needed to proceed to partial data import (regular sync using import files) on a pre-production environment from a third party service that didn't anonymize its own data. Having this command would have allowed us to proceed to selective data anonymization after each sync and keep sensitive data out without running a full database anonymization.

There are probably other existing use cases.

Original copy/paste from our internal bug tracker, in french from @SimonMellerin:

> Lors de la configuration de l’anonymisation, on pourrait ajouter une notion de `collection`
> 
> ```yml
> anonymization:
>     default:
>       user:
>         prenom: 
>           anonymizer: fr_fr.prenom
>           collection: my_collection
>         nom: fr_fr.nom
> ```
> 
> ensuite on pourrait lancer un `console db-tools:anonymize -c my_collection` pour anonymiser uniquement cette collection.
> 
> Le use-case que je vois c'est : j'ai des données de synchronisées avec une API externe, mais sur leur env de test, bin ils nous renvoient des vraies données. Après synchro des données en provenance de cette API, on pourrait lancer l'anonymisation uniquement sur les targets concernées. Pratique pour ne pas envoyer des mails ou des SMS à des vrais endusers
